"""TRINETRA ML - TFLite to C Array Exporter for ESP32-S3 Firmware.

Converts models/trinetra_ds_cnn_int8.tflite to a 16-byte aligned C/C++ byte array header.
"""

from __future__ import annotations

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def export_tflite_to_c_array(
    tflite_path: str | Path = PROJECT_ROOT / "TRINETRA_ML" / "models" / "trinetra_ds_cnn_int8.tflite",
    output_header_path: str | Path = PROJECT_ROOT / "firmware" / "main" / "model_data.h",
) -> dict:
    tflite_path = Path(tflite_path)
    output_header_path = Path(output_header_path)
    output_header_path.parent.mkdir(parents=True, exist_ok=True)

    if not tflite_path.exists():
        raise FileNotFoundError(f"TFLite model not found: {tflite_path}")

    with open(tflite_path, "rb") as f:
        model_bytes = f.read()

    file_size = len(model_bytes)

    # Format bytes as hex array (12 bytes per line)
    hex_lines = []
    for i in range(0, file_size, 12):
        chunk = model_bytes[i:i + 12]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        hex_lines.append(f"    {hex_str},")

    c_array_content = "\n".join(hex_lines)

    header_content = f"""// AUTO-GENERATED BY TRINETRA ML - STAGE 6 EXPORTER
// Model Source: {tflite_path.name}
// Original Size: {file_size} bytes ({file_size / 1024.0:.2f} KB)
// DO NOT EDIT MANUALLY

#ifndef TRINETRA_MODEL_DATA_H_
#define TRINETRA_MODEL_DATA_H_

#include <cstdint>

#ifdef __cplusplus
extern "C" {{
#endif

// Align model data to 16 bytes for hardware vectorization / TFLite Micro
alignas(16) const unsigned char g_trinetra_model_data[] = {{
{c_array_content}
}};

const unsigned int g_trinetra_model_data_size = {file_size};

#ifdef __cplusplus
}}
#endif

#endif // TRINETRA_MODEL_DATA_H_
"""

    with open(output_header_path, "w", encoding="utf-8") as f:
        f.write(header_content)

    print(f"[EXPORT-C] Converted {tflite_path.name} -> {output_header_path}")
    print(f"[EXPORT-C] Original .tflite size: {file_size} bytes ({file_size / 1024.0:.2f} KB)")
    print(f"[EXPORT-C] C-array elements:      {file_size} bytes")

    return {
        "source_file": str(tflite_path),
        "target_file": str(output_header_path),
        "size_bytes": file_size,
        "size_kb": file_size / 1024.0,
    }


if __name__ == "__main__":
    export_tflite_to_c_array()
